version: 2

env:
  - IMAGE_NAME=ghcr.io/flohoss/godash

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - use: buildx
    dockerfile: docker/goreleaser.dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - '{{ .Env.IMAGE_NAME }}:latest-amd64'
      - '{{ .Env.IMAGE_NAME }}:v{{ .Major }}-amd64'
      - '{{ .Env.IMAGE_NAME }}:{{ .Tag }}-amd64'
    build_flag_templates:
      - '--build-arg=DATE={{ .Date }}'
      - '--build-arg=VERSION={{ .Tag }}'
      - '--platform=linux/amd64'
    extra_files:
      - views/
      - package.json
      - yarn.lock
      - tailwind.config.js
      - docker/entrypoint.sh
      - assets/
  - use: buildx
    dockerfile: docker/goreleaser.dockerfile
    goos: linux
    goarch: arm64
    image_templates:
      - '{{ .Env.IMAGE_NAME }}:latest-arm64v8'
      - '{{ .Env.IMAGE_NAME }}:v{{ .Major }}-arm64v8'
      - '{{ .Env.IMAGE_NAME }}:{{ .Tag }}-arm64v8'
    build_flag_templates:
      - '--build-arg=DATE={{ .Date }}'
      - '--build-arg=VERSION={{ .Tag }}'
      - '--platform=linux/arm64/v8'
    extra_files:
      - views/
      - package.json
      - yarn.lock
      - tailwind.config.js
      - docker/entrypoint.sh
      - assets/

docker_manifests:
  - name_template: '{{ .Env.IMAGE_NAME }}:{{ .Tag }}'
    image_templates:
      - '{{ .Env.IMAGE_NAME }}:{{ .Tag }}-amd64'
      - '{{ .Env.IMAGE_NAME }}:{{ .Tag }}-arm64v8'
  - name_template: '{{ .Env.IMAGE_NAME }}:v{{ .Major }}'
    image_templates:
      - '{{ .Env.IMAGE_NAME }}:v{{ .Major }}-amd64'
      - '{{ .Env.IMAGE_NAME }}:v{{ .Major }}-arm64v8'
  - name_template: '{{ .Env.IMAGE_NAME }}:latest'
    image_templates:
      - '{{ .Env.IMAGE_NAME }}:latest-amd64'
      - '{{ .Env.IMAGE_NAME }}:latest-arm64v8'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - formats: ['none']

release:
  skip_upload: true
