services:
  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        GOLANG_VERSION: "1.20"
    command: air --build.exclude_dir "static,docs,storage,tmp,dist,logs"
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=debug
      - TITLE=DEV
    ports:
      - 4000:4000
    volumes:
      - ./src:/src/
