services:
  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        - GOLANG_VERSION=${GOLANG_VERSION}
    command: air -c .air.toml
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=debug
      - TITLE=DEV
    ports:
      - 4000:4000
    volumes:
      - ./src:/src/
