name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: git.unjx.de/${{ github.repository }}
          tags: |
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=GoDash
            org.opencontainers.image.description=Blasing fast start page for your services
            org.opencontainers.image.vendor=Unjx
      - name: Login to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.unjx.de
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            V_GOLANG=${{ vars.V_GOLANG }}
            V_NODE=${{ vars.V_NODE }}
            V_ALPINE=${{ vars.V_ALPINE }}
