name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: git.unjx.de
  LATEST_IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}:latest

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.unjx.de
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.LATEST_IMAGE }}
          build-args: |
            V_GOLANG=${{ vars.V_GOLANG }}
            V_NODE=${{ vars.V_NODE }}
            V_ALPINE=${{ vars.V_ALPINE }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.token }}
