ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}-alpine
RUN apk add tzdata

# GoDash
WORKDIR /app
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download

# Air
RUN go install github.com/cosmtrek/air@latest
COPY ./.air.toml .

# Envs
ENV APP_VERSION=v0.0.1-dev
ENV BUILD_TIME=2023-04-05T20:48:07Z
