variables:
  LATEST_IMAGE: '$CI_REGISTRY_IMAGE:latest'
  DOCKER_VERSION: '24.0.2'
  GOLANG_VERSION: '1.20'
  NODE_VERSION: '18'
  ALPINE_VERSION: '3'
  DEBIAN_VERSION: '12'
  TELEPORT_VERSION: '13.1.1'

image: docker:$DOCKER_VERSION-git

.login_registry:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  cache:
    paths:
      - .go/pkg/mod/
