.if-release-candidate-tag: &if-release-candidate-tag
  if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+/'

.if-stable-release-tag: &if-stable-release-tag
  if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'

.if-default-branch: &if-default-branch
  if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.rules:release:
  rules:
    - <<: *if-release-candidate-tag
    - <<: *if-stable-release-tag

.rules:default:
  rules:
    - <<: *if-release-candidate-tag
    - <<: *if-stable-release-tag
    - <<: *if-default-branch
